name: MyPy Check

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  mypy-check:
    name: Check Python code with MyPy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy

      - name: Run MyPy checks
        run: mypy . --ignore-missing-imports --strict
